apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: ai-sandbox
  labels:
    app: transaction-service
spec:
  selector:
    app: transaction-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
