apiVersion: v1
kind: Service
metadata:
  name: survey-service
  namespace: ai-sandbox
  labels:
    app: survey-service
spec:
  selector:
    app: survey-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
